import sqlite3

def connect_database(database_name):
    conn = sqlite3.connect(database_name)
    return conn

def create_cursor(conn):
    cursor = conn.cursor()
    return cursor

def create_tables(cursor):
    # PK is Primary Key and FK is Foreign Key
    
    # PK is ROWID (automatically generated by SQLite)
    cursor.execute('''
        CREATE TABLE IF NOT EXISTS contacts 
                   (first_name text, last_name text, address text)
                   ''')
    
    # PK is ROWID (automatically generated by SQLite)    
    cursor.execute('''
        CREATE TABLE IF NOT EXISTS contact_types 
                   (type_name text)
                   ''')
    
    # PK is ROWID (automatically generated by SQLite)
    # FK contact_id --> PK (ROWID) of contacts
    # FK type_id --> PK (ROWID) of contact_types
    cursor.execute('''
        CREATE TABLE IF NOT EXISTS contact_details 
                   (contact_id integer, type_id integer, contact text)
                   ''')
    